apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - name: blue-green
        image: arimas/blue_green:latest
        imagePullPolicy: Always
        env:
        - name: OUTPUT_WORD
          value: "Demo App"
      - name: apache-exporter
        image: lusotycoon/apache-exporter
