apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - image: arima-sample-apps-registry.ap-southeast-1.cr.aliyuncs.com/blue-green/blue-green:latest
      #- image: arima-sample-apps-registry-vpc.ap-southeast-1.cr.aliyuncs.com/blue-green/blue-green:latest
        name: blue-green
        imagePullPolicy: Always
        env:
        - name: OUTPUT_WORD
          value: "Demo App"
