apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: arimas/blue_green:blue
        name: blue-green
        env:
        - name: OUTPUT_WORD
          value: "Demo App"
