apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-green
  template:
    metadata:
      labels:
        app: blue-green
    spec:
      containers:
      - image: arima-test-registry-vpc.ap-southeast-1.cr.aliyuncs.com/apps/blue-green:latest
      #- image: arimas/blue_green:latest
        name: blue-green
        imagePullPolicy: Always
        env:
        - name: OUTPUT_WORD
          value: "Demo App"
