apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apache-exporter
spec:
  endpoints:
  - interval: 30s
    port: apache-exporter
    path: /metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: apache-exporter
