apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue-green
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-exporter
  name: apache-exporter
spec:
  ports:
  - name: apache-exporter
    port: 9117
    protocol: TCP
    targetPort: 9117
  type: ClusterIP
  selector:
    app: blue-green
