apiVersion: v1
kind: Service
metadata:
  labels:
    app: blue-green
  name: blue-green
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: blue-green
  type: LoadBalancer
